version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set a root password
      MYSQL_USER: cjz              # Create a user named 'cjz'
      MYSQL_PASSWORD: cjz          # Set the user password to 'cjz'
    ports:
      - "3306:3306"
    volumes:
      - ./hot-off-press-mysql/data:/var/lib/mysql      # Optional: Persist data
      - ./hot-off-press-mysql/initdb:/docker-entrypoint-initdb.d  # Execute SQL scripts on startup

  nacos:
    image: nacos/nacos-server:1.2.0
    container_name: nacos
    restart: always
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
    volumes:
      - ./hot-off-press-nacos/nacos-data:/home/nacos/data


  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9090"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - ./hot-off-press-minio/data:/data
      - ./hot-off-press-minio/config:/root/.minio
    ports:
      - "9000:9000"
      - "9090:9090"
    restart: always

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "--requirepass", "hot-off-press" ]

  zookeeper:
    image: zookeeper:3.4.14
    container_name: zookeeper
    ports:
      - "2181:2181"

  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./hot-off-press-elasticsearch/plugins:/usr/share/elasticsearch/plugins

  mongo-service:
    image: mongo
    container_name: mongo-service
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./hot-off-pres-mongoDB/data/mongodata:/data

#  kafka:
#    image: wurstmeister/kafka:2.12-2.3.1
#    container_name: kafka
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_ZOOKEEPER_CONNECT: 127.0.0.1:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
#    network_mode: host
