version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set a root password
      MYSQL_USER: cjz              # Create a user named 'cjz'
      MYSQL_PASSWORD: cjz          # Set the user password to 'cjz'
    ports:
      - "3306:3306"
    volumes:
      - ./hot-off-press-mysql/data:/var/lib/mysql      # Optional: Persist data
      - ./hot-off-press-mysql/initdb:/docker-entrypoint-initdb.d  # Execute SQL scripts on startup

  nacos:
    image: nacos/nacos-server:1.2.0
    container_name: nacos
    restart: always
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
    volumes:
      - ./hot-off-press-nacos/nacos-data:/home/nacos/data


  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9090"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - ./hot-off-press-minio/data:/data
      - ./hot-off-press-minio/config:/root/.minio
    ports:
      - "9000:9000"
      - "9090:9090"
    restart: always
